#!/usr/bin/env bash
# Types of Networks

# What type of network a computer in local is connected to?

echo "2"

# Type of network a comp in one building to another few strts away
echo "2"

# Network used when browsing www.google.com
echo "1"
