#!/usr/bin/env bash

#  Bash script that displays To infinity and beyond
#+ with a sleep 2
#+ I am invincible!!! when receiving a SIGTERM signal


trap 'echo "I am invincible!!!"' SIGTERM

while True
do
    echo "To infinity and beyond"
done
