#!/usr/bin/env bash
#  This script uses a while loop and if
#+ to display Best School 9 times and Hi
var=1

while [ $var -le 10 ]
do
    echo "Best School"
    if [ $var -eq 9 ]
    then
	echo "Hi"
    fi
    #echo "Best School$var"
    var=$((var+1))
done
