#!/usr/bin/env bash
#  This script displays numbe 1 - 20
#+ at 4 - bad luck from china
#+ at 9 - bad luck Japan
#+ at 17 - bad luck from Italy
var=1

while [ $var -le 20 ]
do
    case $var in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
	*)
	    echo "$var"
	    ;;
    esac
    var=$((var+1))
done
