#!/usr/bin/env bash
#  Bash script that displays time for
#+ 12 hours and 59 minutes

hour=1
minute=1
echo "Hour:$hour"
while [ $hour -lt 13 ]
do
    while [ $minute -le 59 ]
    do
	echo "$minute"
	#minute=$((minute+1))
	if [ $minute -eq 59 ]
	then
	    echo "Hour: $hour"
	fi
	minute=$((minute+1))

    done
    minute=0
    hour=$((hour+1))
done
