#!/usr/bin/env bash
# Script that resolves localhost to 127.0.0.2
# Resolves facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new

sed -i 's/127.*$/127.0.02 localhost\n8.8.8.8 facebook.com/' ~/hosts.new

cat ~/hosts.new > /etc/hosts
